In [22]:
import pandas as pd 
import numpy as np 
import indicators as ind 
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [23]:
try:
    df = pd.read_csv('../data/S & P 500 Assets/daily/AAPL.csv')
except FileNotFoundError:
    print("File Not Fount")
df.head()

         Date      Open      High       Low     Close  Adj Close     Volume
0  2010-01-04  7.622500  7.660714  7.585000  7.643214   6.478998  493729600
1  2010-01-05  7.664286  7.699643  7.616071  7.656429   6.490199  601904800
2  2010-01-06  7.656429  7.686786  7.526786  7.534643   6.386963  552160000
3  2010-01-07  7.562500  7.571429  7.466071  7.520714   6.375156  477131200
4  2010-01-08  7.510714  7.571429  7.466429  7.570714   6.417541  447610800

In [27]:
cols = {"Date":"date","Open":"open","High":"high", "Low":"low","Close":"close","Volume":"volume"}
df.rename(columns=cols, inplace=True)
df.drop('Adj Close',axis=1,inplace=True)
df['date'] = pd.to_datetime(df['date'])
df.head()

KeyError: "['Adj Close'] not found in axis"

In [28]:
df = df.reindex(columns=['date','open','high','low','close', 'volume'])
df['date'] = df['date'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')
df.head()

AttributeError: Can only use .dt accessor with datetimelike values

In [29]:
start = "2015-01-01"
end = "2017-01-01"

filtered_df = df[(df['date'] >= start) & (df['date']<=end)]
filtered_df.head()

,date,open,high,low,close,volume
1258,2015-01-02 00:00:00.000000,27.847500,27.860001,26.837500,27.332500,212818400
1259,2015-01-05 00:00:00.000000,27.072500,27.162500,26.352501,26.562500,257142000
1260,2015-01-06 00:00:00.000000,26.635000,26.857500,26.157499,26.565001,263188400
1261,2015-01-07 00:00:00.000000,26.799999,27.049999,26.674999,26.937500,160423600
1262,2015-01-08 00:00:00.000000,27.307501,28.037500,27.174999,27.972500,237458000

In [33]:
new_df = ind.calc_rsi(filtered_df)
new_df.tail()

/home/sohan/Desktop/Final_Assesment/modules/indicators.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rsi_14'] = 100 - (100 / (rs + 1))
/home/sohan/Desktop/Final_Assesment/modules/indicators.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return df

,date,open,high,low,close,volume,rsi_14,rsi_signal
1757,2016-12-23 00:00:00.000000,28.897499,29.129999,28.897499,29.129999,56998000,84.266166,1
1758,2016-12-27 00:00:00.000000,29.129999,29.450001,29.122499,29.315001,73187600,86.740971,1
1759,2016-12-28 00:00:00.000000,29.379999,29.504999,29.049999,29.190001,83623600,73.113180,1
1760,2016-12-29 00:00:00.000000,29.112499,29.277500,29.100000,29.182501,60158000,74.796503,1
1761,2016-12-30 00:00:00.000000,29.162500,29.299999,28.857500,28.955000,122345200,61.604784,0

In [34]:
new_df = ind.macd_signals(new_df)
new_df.tail()

/home/sohan/Desktop/Final_Assesment/modules/indicators.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/sohan/Desktop/Final_Assesment/modules/indicators.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/home/sohan/Desktop/Final_Assesment/modules/indicators.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,date,open,high,low,close,volume,rsi_14,rsi_signal,macd,macd_sigs,macd_signal
1757,2016-12-23 00:00:00.000000,28.897499,29.129999,28.897499,29.129999,56998000,84.266166,1,0.371249,0.278667,1
1758,2016-12-27 00:00:00.000000,29.129999,29.450001,29.122499,29.315001,73187600,86.740971,1,0.383112,0.308926,1
1759,2016-12-28 00:00:00.000000,29.379999,29.504999,29.049999,29.190001,83623600,73.113180,1,0.378069,0.332592,1
1760,2016-12-29 00:00:00.000000,29.112499,29.277500,29.100000,29.182501,60158000,74.796503,1,0.369211,0.349359,1
1761,2016-12-30 00:00:00.000000,29.162500,29.299999,28.857500,28.955000,122345200,61.604784,0,0.339916,0.358183,0

In [ ]:
new_df.to_csv('indicators_signal.csv')