In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../data/dataset/target_3d_signal.csv')
df.head(10)

,date,open,high,low,close,volume,ema_signal,MACD_signal,ADX,rsi_signal,bb_signal,Keltner_channels,Stochastic_oscillator,target_signal_3d
0,2018-01-02 00:00:00.000000,42.540001,43.075001,42.314999,43.064999,102223600.0,0,0,NaN,0,0,0,0,0
1,2018-01-03 00:00:00.000000,43.132500,43.637501,42.990002,43.057499,118071600.0,-1,-1,NaN,0,0,0,0,0
2,2018-01-04 00:00:00.000000,43.134998,43.367500,43.020000,43.257500,89738400.0,1,1,NaN,0,0,0,0,0
3,2018-01-05 00:00:00.000000,43.360001,43.842499,43.262501,43.750000,94640000.0,1,1,NaN,0,0,0,0,0
4,2018-01-08 00:00:00.000000,43.587502,43.902500,43.482498,43.587502,82271200.0,1,1,NaN,0,0,0,0,0
5,2018-01-09 00:00:00.000000,43.637501,43.764999,43.352501,43.582500,86336000.0,1,1,NaN,0,0,0,0,0
6,2018-01-10 00:00:00.000000,43.290001,43.575001,43.250000,43.572498,95839600.0,1,1,NaN,0,0,0,0,0
7,2018-01-11 00:00:00.000000,43.647499,43.872501,43.622501,43.820000,74670800.0,1,1,NaN,0,0,0,0,0
8,2018-01-12 00:00:00.000000,44.044998,44.340000,43.912498,44.272499,101672400.0,1,1,NaN,0,0,-1,0,0
9,2018-01-16 00:00:00.000000,44.474998,44.847500,44.035000,44.047501,118263600.0,1,1,NaN,0,0,0,0,0

In [5]:
df.isna().sum()

date                     0
open                     0
high                     0
low                      0
close                    0
volume                   0
ema_signal               0
MACD_signal              0
ADX                      0
rsi_signal               0
bb_signal                0
Keltner_channels         0
Stochastic_oscillator    0
target_signal_3d         0
dtype: int64

In [4]:
df.dropna(inplace=True)

In [7]:
signals = []
rsi_signal = df['rsi_signal'].tolist()
macd_signal = df['MACD_signal'].tolist()
ema_signal = df['ema_signal'].tolist()
bb_signal = df['bb_signal'].tolist()
keltner_channels = df['Keltner_channels'].tolist()
stochastic_oscillator = df['Stochastic_oscillator'].tolist()
adx_val = df['ADX'].tolist()
target_signal = df['target_signal_3d'].tolist()

for i in range(df.shape[0]):
    if adx_val[i] > 30:
        if (ema_signal == 1 or rsi_signal == 1) and target_signal == 1:
            signals.append(1)
        elif (ema_signal == -1 or rsi_signal == -1) and target_signal == -1:
            signals.append(-1)
        else:
            signals.append(0)
    else:
        if (rsi_signal == 1 or bb_signal == 1) and (keltner_channels == 1 or stochastic_oscillator == 1) and target_signal == 1:
            signals.append(1)
        elif (rsi_signal == -1 or bb_signal == -1) and (keltner_channels == -1 or stochastic_oscillator == -1) and target_signal == -1:
            signals.append(-1)
        else:
            signals.append(0)

df["final_signal"] = signals

In [9]:
df.tail(10)

,date,open,high,low,close,volume,ema_signal,MACD_signal,ADX,rsi_signal,bb_signal,Keltner_channels,Stochastic_oscillator,target_signal_3d,final_signal
1249,2022-12-16 00:00:00.000000,136.690002,137.649994,133.729996,134.509995,160156900.0,-1,-1,15.941106,1,1,1,1,0,0
1250,2022-12-19 00:00:00.000000,135.110001,135.199997,131.320007,132.369995,79592600.0,-1,-1,16.568604,1,1,1,1,0,0
1251,2022-12-20 00:00:00.000000,131.389999,133.250000,129.889999,132.300003,77432800.0,-1,-1,17.175160,1,0,1,1,0,0
1252,2022-12-21 00:00:00.000000,132.979996,136.809998,132.750000,135.449997,85928000.0,-1,-1,18.399059,0,0,0,0,-1,0
1253,2022-12-22 00:00:00.000000,134.350006,134.559998,130.300003,132.229996,77852100.0,-1,-1,19.235715,1,0,1,1,-1,0
1254,2022-12-23 00:00:00.000000,130.919998,132.419998,129.639999,131.860001,63814900.0,-1,-1,21.617660,0,0,0,1,-1,0
1255,2022-12-27 00:00:00.000000,131.380005,131.410004,128.720001,130.029999,69007800.0,-1,-1,21.912949,0,0,1,1,0,0
1256,2022-12-28 00:00:00.000000,129.669998,131.029999,125.870003,126.040001,85438400.0,-1,-1,22.241540,1,0,1,1,0,0
1257,2022-12-29 00:00:00.000000,127.989998,130.479996,127.730003,129.610001,75703700.0,-1,-1,22.362558,0,0,0,1,0,0
1258,2022-12-30 00:00:00.000000,128.410004,129.949997,127.430000,129.929993,77034200.0,-1,-1,23.356171,0,0,0,1,0,0

In [11]:
df['target_signal_3d'].value_counts()

 0    589
 1    364
-1    280
Name: target_signal_3d, dtype: int64

In [4]:
X = df.drop(['date','target_signal_3d'],axis=1)
y = df['target_signal_3d']

In [6]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

rf_classifier.fit(X_train, y_train)

predictions = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

Accuracy: 0.5564516129032258

In [11]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(base_estimator=DecisionTreeClassifier()
                           ,n_estimators=100
                           ,max_samples=0.8
                           ,oob_score=True
                           ,random_state=0)

bag_model.fit(X_train,y_train)
bag_model.oob_score_

0.5231854838709677

In [12]:
from sklearn.linear_model import LogisticRegression
bag_model = BaggingClassifier(base_estimator=LogisticRegression()
                           ,n_estimators=100
                           ,max_samples=0.8
                           ,oob_score=True
                           ,random_state=0)

bag_model.fit(X_train,y_train)
bag_model.oob_score_

0.5211693548387096

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from talib import RSI, SMA

# Load stock price data
stock_data = pd.read_csv('stock_data.csv')

# Calculate technical indicators (Moving Average and RSI)
stock_data['SMA_50'] = SMA(stock_data['Close'], timeperiod=50)
stock_data['RSI_14'] = RSI(stock_data['Close'], timeperiod=14)

# Define trading signals based on indicators
stock_data['Signal'] = np.where((stock_data['Close'] > stock_data['SMA_50']) & (stock_data['RSI_14'] > 70), 1, 0)

# Prepare features and target variable
X = stock_data[['SMA_50', 'RSI_14']].values
y = stock_data['Signal'].values

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the Random Forest classifier
rf_classifier = RandomForestClassifier()

# Define parameter grid for GridSearchCV
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10]
}

# Perform grid search for parameter tuning
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=3, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Get the best model from grid search
best_rf_model = grid_search.best_estimator_

# Make predictions on the testing set
predictions = best_rf_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

In [ ]:
import pandas as pd

# Load data
data = pd.read_csv('data.csv')

# Compute correlation matrix
correlation_matrix = data.corr()

# Extract correlation values with the target variable
correlation_with_target = correlation_matrix['target_variable'].abs().sort_values(ascending=False)

# Select top features based on correlation
top_features_correlation = correlation_with_target[correlation_with_target > 0.5].index.tolist()

from sklearn.feature_selection import mutual_info_classif

# Load data
X = data.drop(columns=['target_variable'])
y = data['target_variable']

# Calculate mutual information scores
mutual_info_scores = mutual_info_classif(X, y)

# Select top features based on mutual information
top_features_mutual_info = X.columns[np.argsort(mutual_info_scores)[::-1]][:10].tolist()

from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

# Load data
X = data.drop(columns=['target_variable'])
y = data['target_variable']

# Initialize Random Forest classifier
rf_classifier = RandomForestClassifier()

# Initialize RFE
rfe = RFE(estimator=rf_classifier, n_features_to_select=10, step=1)

# Fit RFE
rfe.fit(X, y)

# Select top features based on RFE
top_features_rfe = X.columns[rfe.support_].tolist()