In [1]:
import pandas as pd
import numpy as np

In [2]:
stock_tickers = [
    "AAPL", "ABT", "ADBE", "AEP", "AES", "AFL", "ALGN", "AMD", "AMT", "AOS",
    "APA", "APD", "ARE", "AWK", "AXON", "BA", "BAC", "BAX", "BDX", "BG",
    "BKR", "BRK-B", "BX", "BXP", "CAT", "CCI", "CDNS", "CE", "CEG", "COF",
    "CPB", "CPT", "DIS", "EA", "FMC", "FOX", "GOOGL", "IFF", "KLAC", "LNT",
    "MMM", "MO", "NVDA", "STZ", "TECH", "TRGP", "VLO", "WBD", "WMB", "WMT"]

In [3]:
combined_df = pd.DataFrame()
for ticker in stock_tickers:
    stock_df = pd.read_csv(f'../data/S & P 50/{ticker}.csv')
    stock_df['Ticker'] = ticker  # Add a column to identify the stock
    combined_df = pd.concat([combined_df, stock_df])

In [7]:
combined_df.tail(10)

,date,open,high,low,close,volume,Ticker
61622,2022-12-16 00:00:00.000000,144.479996,144.720001,142.570007,142.750000,13447700.0,WMT
61623,2022-12-19 00:00:00.000000,143.009995,143.559998,141.729996,142.800003,5022500.0,WMT
61624,2022-12-20 00:00:00.000000,142.919998,144.639999,142.250000,144.050003,5669800.0,WMT
61625,2022-12-21 00:00:00.000000,144.320007,145.940002,144.259995,145.179993,4575500.0,WMT
61626,2022-12-22 00:00:00.000000,144.770004,144.979996,141.929993,143.479996,4360800.0,WMT
61627,2022-12-23 00:00:00.000000,143.050003,143.800003,142.279999,143.770004,3182500.0,WMT
61628,2022-12-27 00:00:00.000000,144.039993,144.449997,143.190002,143.809998,3348200.0,WMT
61629,2022-12-28 00:00:00.000000,143.470001,143.669998,140.910004,141.289993,5082100.0,WMT
61630,2022-12-29 00:00:00.000000,142.139999,143.020004,141.750000,142.149994,3057300.0,WMT
61631,2022-12-30 00:00:00.000000,141.559998,141.990005,140.809998,141.789993,3835300.0,WMT

In [6]:
combined_df.reset_index(drop=True, inplace=True)

In [8]:
combined_df.to_csv('../data/dataset/combined_stocks_data.csv',index=False)